"""add_anomalias_presupuestales

Revision ID: b83881bd8d42
Revises: 001_add_precio_index
Create Date: 2026-03-21 17:23:42.161501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83881bd8d42'
down_revision = '001_add_precio_index'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalias_presupuestales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('inciso', sa.String(length=10), nullable=False),
    sa.Column('nombre_organismo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('severidad', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('valor_observado', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('valor_umbral', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('detectado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes', 'inciso', 'tipo', name='_anomalia_periodo_tipo_uc')
    )
    op.create_index(op.f('ix_anomalias_presupuestales_anio'), 'anomalias_presupuestales', ['anio'], unique=False)
    op.create_index(op.f('ix_anomalias_presupuestales_detectado_en'), 'anomalias_presupuestales', ['detectado_en'], unique=False)
    op.create_index(op.f('ix_anomalias_presupuestales_id'), 'anomalias_presupuestales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_precio_producto_id_fecha', 'precios', ['producto_id', 'fecha'], unique=False)
    op.create_table('alertas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('umbral_cambio', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alertas_id', 'alertas', ['id'], unique=False)
    op.drop_index(op.f('ix_anomalias_presupuestales_id'), table_name='anomalias_presupuestales')
    op.drop_index(op.f('ix_anomalias_presupuestales_detectado_en'), table_name='anomalias_presupuestales')
    op.drop_index(op.f('ix_anomalias_presupuestales_anio'), table_name='anomalias_presupuestales')
    op.drop_table('anomalias_presupuestales')
    # ### end Alembic commands ###
