"""add_indicadores_macro

Revision ID: fb678510120a
Revises: b83881bd8d42
Create Date: 2026-03-21 20:36:55.704316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb678510120a'
down_revision = 'b83881bd8d42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicadores_macro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unidad', sa.String(length=100), nullable=True),
    sa.Column('fuente', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', 'anio', name='_macro_codigo_anio_uc')
    )
    op.create_index(op.f('ix_indicadores_macro_anio'), 'indicadores_macro', ['anio'], unique=False)
    op.create_index(op.f('ix_indicadores_macro_codigo'), 'indicadores_macro', ['codigo'], unique=False)
    op.create_index(op.f('ix_indicadores_macro_id'), 'indicadores_macro', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicadores_macro_id'), table_name='indicadores_macro')
    op.drop_index(op.f('ix_indicadores_macro_codigo'), table_name='indicadores_macro')
    op.drop_index(op.f('ix_indicadores_macro_anio'), table_name='indicadores_macro')
    op.drop_table('indicadores_macro')
    # ### end Alembic commands ###
